In [1]:
import numpy as np
from sklearn.metrics import mean_absolute_error

In [2]:
# Creating dataset
rows, cols = 10, 10
dataset = []

for i in range(1, rows + 1):
    for j in range(1, cols +1 ):
        dataset.append([i, j, i * j])

dataset = np.array(dataset)
print(dataset)

[[  1   1   1]
 [  1   2   2]
 [  1   3   3]
 [  1   4   4]
 [  1   5   5]
 [  1   6   6]
 [  1   7   7]
 [  1   8   8]
 [  1   9   9]
 [  1  10  10]
 [  2   1   2]
 [  2   2   4]
 [  2   3   6]
 [  2   4   8]
 [  2   5  10]
 [  2   6  12]
 [  2   7  14]
 [  2   8  16]
 [  2   9  18]
 [  2  10  20]
 [  3   1   3]
 [  3   2   6]
 [  3   3   9]
 [  3   4  12]
 [  3   5  15]
 [  3   6  18]
 [  3   7  21]
 [  3   8  24]
 [  3   9  27]
 [  3  10  30]
 [  4   1   4]
 [  4   2   8]
 [  4   3  12]
 [  4   4  16]
 [  4   5  20]
 [  4   6  24]
 [  4   7  28]
 [  4   8  32]
 [  4   9  36]
 [  4  10  40]
 [  5   1   5]
 [  5   2  10]
 [  5   3  15]
 [  5   4  20]
 [  5   5  25]
 [  5   6  30]
 [  5   7  35]
 [  5   8  40]
 [  5   9  45]
 [  5  10  50]
 [  6   1   6]
 [  6   2  12]
 [  6   3  18]
 [  6   4  24]
 [  6   5  30]
 [  6   6  36]
 [  6   7  42]
 [  6   8  48]
 [  6   9  54]
 [  6  10  60]
 [  7   1   7]
 [  7   2  14]
 [  7   3  21]
 [  7   4  28]
 [  7   5  35]
 [  7   6  42]
 [  7   7 

In [3]:
# Normalizing dataset
normalized = dataset / 100

In [4]:
# Shuffle and split dataset
np.random.shuffle(normalized)

# Calculate split index
split_ratio = 0.7
split_i= int(len(normalized) * split_ratio)

# Split the dataset
train_data = normalized[:split_i]
test_data = normalized[split_i:]



In [5]:
# Parameters
input_size = 2
hidden_size = 8
output_size = 1
learning_rate = 0.03
epochs = 10000 

In [6]:
#  initializing weights
hidden_input = np.random.uniform(low=-np.sqrt(6 / (input_size + hidden_size)),
                                          high=np.sqrt(6 / (input_size + hidden_size)),
                                          size=(input_size, hidden_size))

hidden_output = np.random.uniform(low=-np.sqrt(6 / (hidden_size + output_size)),
                                           high=np.sqrt(6 / (hidden_size + output_size)),
                                           size=(hidden_size, output_size))

In [ ]:
# Initialize biases to zero
bias_hidden = np.zeros((1, hidden_size))
bias_output = np.zeros((1, output_size))

In [ ]:
# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [ ]:
# Derivative of the sigmoid activation function
def sigmoid_derivative(x):
    return x * (1 - x)

In [ ]:
# Training
for epoch in range(epochs):
    # Forward pass
    hidden_layer_input = np.dot(train_data[:, :input_size], hidden_input) + bias_hidden
    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_output, hidden_output) + bias_output
    predicted_output = sigmoid(output_layer_input)

    # Error calculation
    error = train_data[:, input_size:] - predicted_output

    # Backpropagation
    output_delta = error * sigmoid_derivative(predicted_output)
    hidden_error = output_delta.dot(hidden_output.T)
    hidden_delta = hidden_error * sigmoid_derivative(hidden_layer_output)

    # Update weights and biases
    hidden_output += hidden_layer_output.T.dot(output_delta) * learning_rate
    hidden_input += train_data[:, :input_size].T.dot(hidden_delta) * learning_rate

    print(f"Error: {error}")

In [ ]:
# Testing
hidden_layer_input_test = np.dot(test_data[:, :input_size], hidden_input) + bias_hidden
hidden_layer_output_test = sigmoid(hidden_layer_input_test)

output_layer_input_test = np.dot(hidden_layer_output_test, hidden_output) + bias_output
predicted_output_test = sigmoid(output_layer_input_test)

# Convert predictions back to the original scale
predicted_output_test = predicted_output_test * 100

# Print real and predicted values, mean squared errors, and accuracy
correct_predictions = 0

for i in range(len(test_data)):
    real_value = test_data[i, input_size] * 100
    predicted_value = predicted_output_test[i, 0]
    score = mean_absolute_error(np.array([real_value]), np.array([predicted_value]))
    
    print(f" {test_data[i][0]*100} x {test_data[i][1]*100} Predicted: {predicted_value:.2f}, Real: {real_value:.2f}, Mean Absolute Error: {score:.4f}")

 9.0 x 3.0 Predicted: 29.99, Real: 27.00, Mean Absolute Error: 2.9900
 4.0 x 8.0 Predicted: 30.13, Real: 32.00, Mean Absolute Error: 1.8674
 6.0 x 4.0 Predicted: 17.52, Real: 24.00, Mean Absolute Error: 6.4769
 10.0 x 6.0 Predicted: 62.84, Real: 60.00, Mean Absolute Error: 2.8433
 1.0 x 2.0 Predicted: 1.67, Real: 2.00, Mean Absolute Error: 0.3330
 2.0 x 8.0 Predicted: 17.59, Real: 16.00, Mean Absolute Error: 1.5935
 8.0 x 7.000000000000001 Predicted: 54.73, Real: 56.00, Mean Absolute Error: 1.2676
 8.0 x 1.0 Predicted: 12.92, Real: 8.00, Mean Absolute Error: 4.9162
 3.0 x 9.0 Predicted: 30.16, Real: 27.00, Mean Absolute Error: 3.1564
 6.0 x 9.0 Predicted: 54.80, Real: 54.00, Mean Absolute Error: 0.7989
 6.0 x 6.0 Predicted: 30.08, Real: 36.00, Mean Absolute Error: 5.9197
 1.0 x 6.0 Predicted: 6.79, Real: 6.00, Mean Absolute Error: 0.7924
 5.0 x 8.0 Predicted: 37.90, Real: 40.00, Mean Absolute Error: 2.0978
 5.0 x 10.0 Predicted: 54.83, Real: 50.00, Mean Absolute Error: 4.8287
 5.0 x 6.